# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/GarbageCollector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/GarbageCollector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/GarbageCollector/CMakeFiles /workspaces/GarbageCollector//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/GarbageCollector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GarbageCollector

# Build rule for target.
GarbageCollector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GarbageCollector
.PHONY : GarbageCollector

# fast build rule for target.
GarbageCollector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/build
.PHONY : GarbageCollector/fast

Api.o: Api.cpp.o
.PHONY : Api.o

# target to build an object file
Api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/Api.cpp.o
.PHONY : Api.cpp.o

Api.i: Api.cpp.i
.PHONY : Api.i

# target to preprocess a source file
Api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/Api.cpp.i
.PHONY : Api.cpp.i

Api.s: Api.cpp.s
.PHONY : Api.s

# target to generate assembly for a file
Api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/Api.cpp.s
.PHONY : Api.cpp.s

SpecCollector.o: SpecCollector.cpp.o
.PHONY : SpecCollector.o

# target to build an object file
SpecCollector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecCollector.cpp.o
.PHONY : SpecCollector.cpp.o

SpecCollector.i: SpecCollector.cpp.i
.PHONY : SpecCollector.i

# target to preprocess a source file
SpecCollector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecCollector.cpp.i
.PHONY : SpecCollector.cpp.i

SpecCollector.s: SpecCollector.cpp.s
.PHONY : SpecCollector.s

# target to generate assembly for a file
SpecCollector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecCollector.cpp.s
.PHONY : SpecCollector.cpp.s

SpecParser.o: SpecParser.cpp.o
.PHONY : SpecParser.o

# target to build an object file
SpecParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecParser.cpp.o
.PHONY : SpecParser.cpp.o

SpecParser.i: SpecParser.cpp.i
.PHONY : SpecParser.i

# target to preprocess a source file
SpecParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecParser.cpp.i
.PHONY : SpecParser.cpp.i

SpecParser.s: SpecParser.cpp.s
.PHONY : SpecParser.s

# target to generate assembly for a file
SpecParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/SpecParser.cpp.s
.PHONY : SpecParser.cpp.s

base64.o: base64.cpp.o
.PHONY : base64.o

# target to build an object file
base64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/base64.cpp.o
.PHONY : base64.cpp.o

base64.i: base64.cpp.i
.PHONY : base64.i

# target to preprocess a source file
base64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/base64.cpp.i
.PHONY : base64.cpp.i

base64.s: base64.cpp.s
.PHONY : base64.s

# target to generate assembly for a file
base64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/base64.cpp.s
.PHONY : base64.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GarbageCollector.dir/build.make CMakeFiles/GarbageCollector.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GarbageCollector"
	@echo "... Api.o"
	@echo "... Api.i"
	@echo "... Api.s"
	@echo "... SpecCollector.o"
	@echo "... SpecCollector.i"
	@echo "... SpecCollector.s"
	@echo "... SpecParser.o"
	@echo "... SpecParser.i"
	@echo "... SpecParser.s"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

