FROM registry.altlinux.org/alt/alt:latest
#RUN npm install -g eslint prettier
RUN apt-get update
RUN apt-get install gcc gcc-c++ cmake make libcurl libcurl-devel json-cpp jsoncpp-devel libjsoncpp19 rpmspec