name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: apt-get install -y libcurl4-openssl-dev libjsoncpp-dev
    - name: mk build
      run: rm -rf ./build && mkdir build
    - name: build
      run: cd build && cmake .. && make
    - name: run
      run: ./build/GarbageCollector
